name: clonar_app
description: A Flutter app for shopping, styling, and cloning fashion agents.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  http: ^1.1.0
  table_calendar: ^3.0.9
  url_launcher: ^6.2.2
  image_picker: ^1.0.4
  google_maps_flutter: ^2.5.0
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  crypto: ^3.0.6
  syncfusion_flutter_datepicker: ^24.1.41
  webview_flutter: ^4.4.2
  speech_to_text: ^7.0.0
  permission_handler: ^11.1.0
  intl: ^0.19.0
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/
